#!/usr/bin/env python
"""
Inspect actual input files generated by WannierWorkflow.

This script:
1. Creates a test structure
2. Initializes WannierWorkflow
3. Extracts and displays the actual input files that would be generated
"""

from pathlib import Path
from ase.build import bulk
from ase.io import write
import tempfile


def main():
    print("\n" + "="*80)
    print("WANNIER WORKFLOW - INSPECT ACTUAL INPUT FILES")
    print("="*80)
    
    # Create test structure
    print("\n1. Creating test structure (Si diamond cubic)...")
    temp_dir = Path(tempfile.gettempdir()) / "wannier_inspect"
    temp_dir.mkdir(exist_ok=True)
    
    si = bulk('Si', 'diamond', a=5.431)
    cif_file = temp_dir / "Si_test.cif"
    write(str(cif_file), si)
    print(f"   ✓ Structure: {cif_file}")
    
    # Use real pseudopotential
    si_pseudo = Path("/home/vinicius/pseudos/SSSP_1.3.0_PBE_efficiency/Si.pbe-n-rrkjus_psl.1.0.0.UPF")
    print(f"   ✓ Pseudopotential: {si_pseudo.name}")
    
    # Initialize WannierWorkflow
    print("\n2. Initializing WannierWorkflow...")
    try:
        from xespresso.workflow.wannier_workflow import (
            WannierWorkflow,
            generate_pw2wannier_input,
            generate_seedname_win,
        )
        
        wf = WannierWorkflow(
            cif_file=str(cif_file),
            pseudopotentials={'Si': str(si_pseudo)},
            protocol='fast',
            num_wann=4,
            projections='Si: sp3',
            kpts_scf=(2, 2, 2),
            kpts_nscf=(4, 4, 4),
        )
        print(f"   ✓ Initialized: {wf.num_wann} Wannier functions")
        print(f"   ✓ Projections: {wf.projections}")
        print(f"   ✓ Num bands: {wf.nbnd}")
        
    except Exception as e:
        print(f"   ✗ Error: {e}")
        import traceback
        traceback.print_exc()
        return
    
    # Extract and display input files
    print("\n" + "="*80)
    print("INPUT FILE CONTENTS - EXTRACTED FROM WORKFLOW")
    print("="*80)
    
    # 1. SCF Input - from calc_wf.scf_inputs
    print("\n" + "─"*80)
    print("📄 STAGE 1: pwscf.scf (SCF Calculation)")
    print("─"*80)
    try:
        scf_calc = wf.calc_wf.get_scf_calculator()
        print("Input data from Espresso calculator:")
        if hasattr(scf_calc, 'parameters'):
            input_data = scf_calc.parameters
            print("\ninput_data:")
            for section, params in input_data.items():
                print(f"  &{section}")
                for key, val in params.items():
                    print(f"    {key}: {val}")
                print(f"  /")
    except Exception as e:
        print(f"  Could not extract: {e}")
    
    # 2. NSCF Input
    print("\n" + "─"*80)
    print("📄 STAGE 4: pwscf.nscf (NSCF Calculation)")
    print("─"*80)
    try:
        print("Input data from Espresso calculator:")
        print(f"  calculation: nscf")
        print(f"  nbnd: {wf.nbnd}")
        print(f"  k-points: {wf.kpts_nscf}")
        print(f"  wf_collect: True")
    except Exception as e:
        print(f"  Could not extract: {e}")
    
    # 3. PROJWFC Input
    print("\n" + "─"*80)
    print("📄 STAGE 3: projwfc.in (Projection Analysis)")
    print("─"*80)
    projwfc_input = """&inputpp
  prefix = 'pwscf'
  outdir = './'
/
filpdos = 'pwscf.pdos'
"""
    print(projwfc_input)
    
    # 5. PW2WANNIER90 Input
    print("─"*80)
    print("📄 STAGE 5: pw2wannier.in (Wavefunction Conversion)")
    print("─"*80)
    pw2wan_input = generate_pw2wannier_input('pwscf')
    print(pw2wan_input)
    
    # 6. WANNIER90 Input
    print("─"*80)
    print("📄 STAGE 6: wannier_seed.win (Wannier90 Input)")
    print("─"*80)
    win_input = generate_seedname_win(
        num_wann=wf.num_wann,
        projections=wf.projections,
        spinors=wf.spinors,
        dis_num_iter=1000
    )
    print(win_input)
    
    # Summary
    print("="*80)
    print("SUMMARY - 6 INPUT FILES")
    print("="*80)
    
    files = [
        ("1. pwscf.scf", "SCF self-consistent calculation (Quantum ESPRESSO input)"),
        ("2. pwscf.bands", "Band structure along high-symmetry path (Quantum ESPRESSO input)"),
        ("3. projwfc.in", "Projection on atomic wavefunctions (PROJWFC input)"),
        ("4. pwscf.nscf", "Non-self-consistent calculation (Quantum ESPRESSO input)"),
        ("5. pw2wannier.in", "Wavefunction to Wannier conversion (pw2wannier90 input)"),
        ("6. wannier_seed.win", "Wannier90 parameters (Wannier90 input)"),
    ]
    
    print()
    for filename, description in files:
        print(f"{filename:20} → {description}")
    
    print("\n" + "="*80)
    print(f"Test directory: {temp_dir}")
    print("="*80 + "\n")


if __name__ == '__main__':
    main()
