#!/usr/bin/env python
"""
Inspect all INPUT FILES that WannierWorkflow generates WITHOUT executing calculations.
Shows the actual input files that would be created.
"""

from pathlib import Path
from ase.build import bulk
from ase.io import write
import tempfile
import os


def main():
    print("\n" + "="*80)
    print("WANNIER WORKFLOW - INSPECT ALL GENERATED INPUT FILES")
    print("="*80)
    
    # Use the directory from previous run
    temp_dir = Path("/tmp/wannier_test")
    
    print(f"\nInspecting directory: {temp_dir}\n")
    
    # List all input files
    print("="*80)
    print("ALL INPUT FILES GENERATED BY WORKFLOW")
    print("="*80)
    
    input_files = sorted(temp_dir.rglob("*.pwi")) + sorted(temp_dir.rglob("*.in"))
    
    if not input_files:
        print("No input files found yet. Running workflow initialization...")
        
        # Initialize workflow
        si = bulk('Si', 'diamond', a=5.431)
        cif_file = temp_dir / "Si.cif"
        write(str(cif_file), si)
        
        si_pseudo = Path("/home/vinicius/pseudos/SSSP_1.3.0_PBE_efficiency/Si.pbe-n-rrkjus_psl.1.0.0.UPF")
        
        from xespresso.workflow.wannier_workflow import WannierWorkflow
        
        wf = WannierWorkflow(
            cif_file=str(cif_file),
            pseudopotentials={'Si': str(si_pseudo)},
            protocol='fast',
            num_wann=4,
            projections='Si: sp3',
            kpts_scf=(2, 2, 2),
            kpts_nscf=(4, 4, 4),
        )
        
        print("✓ Workflow initialized")
        
        # Get calculator to generate input
        calc_wf = wf.calc_wf
        atoms = calc_wf.get_atoms()
        
        from espresso import Espresso
        
        # Create SCF calculator and write input
        scf_calc = Espresso(
            input_data=calc_wf.input_data.copy(),
            pseudopotentials=calc_wf.original_pseudopotentials,
            kpts=wf.kpts_scf,
            calculation='scf',
        )
        scf_calc.atoms = atoms
        scf_calc.write_input(atoms, directory=temp_dir, prefix='test_scf')
        
        # Create NSCF calculator and write input
        nscf_input_data = calc_wf.input_data.copy()
        nscf_input_data['nbnd'] = wf.nbnd
        
        nscf_calc = Espresso(
            input_data=nscf_input_data,
            pseudopotentials=calc_wf.original_pseudopotentials,
            kpts=wf.kpts_nscf,
            calculation='nscf',
        )
        nscf_calc.atoms = atoms
        nscf_calc.write_input(atoms, directory=temp_dir, prefix='test_nscf')
        
        # Generate Wannier inputs
        from xespresso.workflow.wannier_workflow import (
            generate_pw2wannier_input,
            generate_seedname_win,
        )
        
        pw2wan_input = generate_pw2wannier_input('test_scf')
        pw2wan_file = temp_dir / "test_pw2wannier.in"
        pw2wan_file.write_text(pw2wan_input)
        
        win_input = generate_seedname_win(
            num_wann=wf.num_wann,
            projections=wf.projections,
            spinors=wf.spinors,
            dis_num_iter=1000
        )
        win_file = temp_dir / "test_wannier_seed.win"
        win_file.write_text(win_input)
        
        input_files = sorted(temp_dir.rglob("*.pwi")) + sorted(temp_dir.glob("test_*.in")) + sorted(temp_dir.glob("test_*.win"))
    
    # Display each input file
    for i, input_file in enumerate(input_files, 1):
        print(f"\n{'─'*80}")
        print(f"{i}. 📄 {input_file.name}")
        print(f"{'─'*80}\n")
        
        content = input_file.read_text()
        print(content)
    
    # Summary
    print("\n" + "="*80)
    print("SUMMARY")
    print("="*80)
    print(f"\n✓ Total input files: {len(input_files)}")
    for f in input_files:
        size = f.stat().st_size
        print(f"  - {f.name:<40} ({size:>6,} bytes)")
    
    print("\n" + "="*80)
    print("These are the ACTUAL input files that WannierWorkflow generates!")
    print("="*80 + "\n")


if __name__ == '__main__':
    main()
