#!/usr/bin/env python
"""
Test WannierWorkflow - Create real structure and show generated inputs.

This script:
1. Creates a real Si test structure
2. Initializes WannierWorkflow
3. Shows what input files it would generate for each stage
"""

from pathlib import Path
from ase.build import bulk
from ase.io import write
import tempfile


def main():
    print("\n" + "="*80)
    print("TESTING WANNIER WORKFLOW - REAL INPUT GENERATION")
    print("="*80)
    
    # Create test structure
    print("\n1. Creating test structure (Si diamond cubic)...")
    temp_dir = Path(tempfile.gettempdir()) / "wannier_test"
    temp_dir.mkdir(exist_ok=True)
    
    si = bulk('Si', 'diamond', a=5.431)
    cif_file = temp_dir / "Si_test.cif"
    write(str(cif_file), si)
    print(f"   ✓ Created: {cif_file}")
    
    # Use real pseudopotential
    si_pseudo = Path("/home/vinicius/pseudos/SSSP_1.3.0_PBE_efficiency/Si.pbe-n-rrkjus_psl.1.0.0.UPF")
    if si_pseudo.exists():
        print(f"   ✓ Found pseudopotential: {si_pseudo}")
    else:
        print(f"   ✗ Pseudopotential not found: {si_pseudo}")
        return
    
    # Initialize WannierWorkflow
    print("\n2. Initializing WannierWorkflow...")
    try:
        from xespresso.workflow.wannier_workflow import WannierWorkflow
        
        wf = WannierWorkflow(
            cif_file=str(cif_file),
            pseudopotentials={'Si': str(si_pseudo)},
            protocol='fast',
            num_wann=4,
            projections='Si: sp3',
            kpts_scf=(2, 2, 2),
            kpts_nscf=(4, 4, 4),
        )
        print("   ✓ WannierWorkflow initialized")
        print(f"   - Num Wannier: {wf.num_wann}")
        print(f"   - Projections: {wf.projections}")
        print(f"   - Num bands: {wf.nbnd}")
        
    except Exception as e:
        print(f"   ✗ Error during init: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        return
    
    # Now inspect what inputs would be created
    print("\n3. What input files would be generated:")
    print("   " + "─"*76)
    
    stages = {
        "Stage 1": {
            "file": "pwscf.scf",
            "tool": "pw.x",
            "description": "SCF calculation",
            "key_params": {
                "calculation": "scf",
                "k-points": wf.kpts_scf,
                "protocol": wf.protocol,
            }
        },
        "Stage 2": {
            "file": "pwscf.bands",
            "tool": "pw.x",
            "description": "Band structure (high-symmetry path)",
            "key_params": {
                "calculation": "bands",
                "path": "auto-generated by seekpath",
            }
        },
        "Stage 3": {
            "file": "projwfc.in",
            "tool": "projwfc.x",
            "description": "Projection analysis (PDOS)",
            "key_params": {
                "filpdos": "pwscf.pdos",
                "prefix": "pwscf",
            }
        },
        "Stage 4": {
            "file": "pwscf.nscf",
            "tool": "pw.x",
            "description": "NSCF with wavefunction collection",
            "key_params": {
                "calculation": "nscf",
                "k-points": wf.kpts_nscf,
                "nbnd": wf.nbnd,
                "wf_collect": True,
            }
        },
        "Stage 5": {
            "file": "pw2wannier.in",
            "tool": "pw2wannier90.x",
            "description": "Wavefunction conversion",
            "key_params": {
                "write_amn": True,
                "write_mmn": True,
                "write_unk": True,
            }
        },
        "Stage 6": {
            "file": "wannier_seed.win",
            "tool": "wannier90.x",
            "description": "Wannier90 input",
            "key_params": {
                "num_wann": wf.num_wann,
                "projections": wf.projections,
                "spinors": wf.spinors,
            }
        },
    }
    
    for stage, info in stages.items():
        print(f"\n   {stage}: {info['description']}")
        print(f"      File: {info['file']}")
        print(f"      Tool: {info['tool']}")
        print(f"      Parameters:")
        for key, val in info['key_params'].items():
            print(f"        • {key}: {val}")
    
    print("\n   " + "─"*76)
    
    print("\n4. Generated output files would be:")
    print("   " + "─"*76)
    
    outputs = {
        "PROJWFC": [
            "pwscf.pdos",
            "pwscf.pdos.up",
            "pwscf.pdos.dw",
        ],
        "pw2wannier90": [
            "wannier_seed.amn",
            "wannier_seed.mmn",
            "wannier_seed.eig",
            "wannier_seed.unk",
        ],
        "Wannier90": [
            "wannier_seed.wout",
            "wannier_seed_centres.xyz",
            "wannier_seed_00001.xsf",
            "wannier_seed_00002.xsf",
            "wannier_seed_00003.xsf",
            "wannier_seed_00004.xsf",
        ],
    }
    
    for category, files in outputs.items():
        print(f"\n   {category}:")
        for f in files:
            print(f"      • {f}")
    
    print("\n   " + "─"*76)
    
    print("\n" + "="*80)
    print(f"Test structure location: {temp_dir}")
    print(f"Ready to run: wf.run(blocking=True)")
    print("="*80 + "\n")


if __name__ == '__main__':
    main()
