#!/usr/bin/env python3
"""
Inspect existing slabs already generated by your workflow.

Looks for directories like: relax/, au111_convergence/, etc
"""

import os
import sys
import glob
import numpy as np
from ase.io import read

def inspect_directory(directory):
    """Inspect a calculation directory for slab geometry."""
    
    print(f"\n{'='*70}")
    print(f"Directory: {directory}")
    print(f"{'='*70}")
    
    # Look for structure files
    structure_files = glob.glob(os.path.join(directory, '*.pwi')) + \
                     glob.glob(os.path.join(directory, '*.pwo')) + \
                     glob.glob(os.path.join(directory, 'geometry.in')) + \
                     glob.glob(os.path.join(directory, 'POSCAR')) + \
                     glob.glob(os.path.join(directory, '*/POSCAR'))
    
    if not structure_files:
        print(f"  ⚠ No structure files found")
        return
    
    for structure_file in structure_files[:3]:  # Check first 3
        print(f"\n  File: {os.path.basename(structure_file)}")
        
        try:
            # Try to read with ASE
            if structure_file.endswith('.pwi'):
                print("    (QE input - parsing not fully supported)")
                # Try to parse manually
                with open(structure_file, 'r') as f:
                    content = f.read()
                    if 'ATOMIC_POSITIONS' in content:
                        print("    ✓ Contains ATOMIC_POSITIONS")
                    if 'CELL_PARAMETERS' in content:
                        print("    ✓ Contains CELL_PARAMETERS")
            else:
                atoms = read(structure_file)
                print(f"    Atoms: {len(atoms)}")
                
                # Geometry info
                z_pos = atoms.get_positions()[:, 2]
                z_min, z_max = z_pos.min(), z_pos.max()
                slab_thickness = z_max - z_min
                
                print(f"    Z-range: {z_min:.4f} to {z_max:.4f} Å")
                print(f"    Thickness: {slab_thickness:.4f} Å")
                
                # Cell
                cell_z = np.linalg.norm(atoms.cell[2])
                vacuum = cell_z - slab_thickness
                print(f"    Cell z: {cell_z:.4f} Å")
                print(f"    Vacuum: {vacuum:.4f} Å")
                
                # Constraints
                if hasattr(atoms, 'constraints') and atoms.constraints:
                    print(f"    Constraints: YES")
                    for c in atoms.constraints:
                        print(f"      - {c}")
                else:
                    print(f"    Constraints: NO ⚠")
                    
        except Exception as e:
            print(f"    ✗ Error reading: {e}")


def main():
    print("="*70)
    print("SLAB GEOMETRY INSPECTION - Check your existing calculations")
    print("="*70)
    
    # Look for common calculation directories
    search_patterns = [
        'relax/*',
        'au111_convergence/*',
        'au100_convergence/*',
        'au110_convergence/*',
        './*/nlayers*',
        './*/vacuum*',
    ]
    
    directories = []
    for pattern in search_patterns:
        directories.extend(glob.glob(pattern))
    
    # Remove duplicates and filter
    directories = list(set([d for d in directories if os.path.isdir(d)]))
    
    if not directories:
        print("\n✗ No calculation directories found")
        print("\nSearching patterns:")
        for p in search_patterns:
            print(f"  {p}")
        print("\nGenerate slabs first using SlabWorkflow")
        return
    
    print(f"\nFound {len(directories)} calculation directories")
    
    for directory in sorted(directories)[:10]:  # Show first 10
        inspect_directory(directory)
    
    if len(directories) > 10:
        print(f"\n... and {len(directories) - 10} more directories")


if __name__ == '__main__':
    main()
