#!/bin/bash

#SBATCH --job-name=wannier



# Wannier workflow for spin component: down
srun --mpi=pmi2 wannier90.x -pp wannier_dn
srun --mpi=pmi2 pw2wannier90.x  -in Fe_bcc_dn.pw2wannier90i > Fe_bcc_dn.pw2wannier90o
srun --mpi=pmi2 wannier90.x wannier_dn
