#!/bin/bash

#SBATCH --job-name=wannier



# Wannier workflow for spin component: up
srun --mpi=pmi2 wannier90.x -pp wannier_up
srun --mpi=pmi2 pw2wannier90.x  -in Fe_bcc_up.pw2wannier90i > Fe_bcc_up.pw2wannier90o
srun --mpi=pmi2 wannier90.x wannier_up
